### ISSUE TITLE
Broken after Detailer's patch (1.1.6f1)

### ISSUE THREAD

**Issue by kputnins** [zeeshanabid94/ZoningToolkit#1]
The  "Zoning Tool" button no longer works after the update.

Selecting a zoning type before building a road still works though :/

**Comment by zeeshanabid94** [comment]
Hey! Thanks for reaching out! I'll take a look at this issue in the upcoming weeks.

I haven't been playing CS 2 much. Haven't been able to get into it ever since March. But I've heard good things about it after the new patch. So give me sometime to make the changes!

**Comment by kputnins** [comment]
Cool, thanks.

Yeah, the last couple of patches brought me back - the game is a lot better now (not perfect though and still needs mods for a lot of missing/frustrating features).

Also just wanted to say thanks for this mod - imo it's S tier and I really can't play the game without it any more 😂

**Comment by JoeyVinyard** [comment]
I did some investigation as to exactly what broke with the detailers patch. It looks as though how ProxyActions work may have changed and that input from the mouse is no longer being detected properly

**Comment by zeeshanabid94** [comment]
Interesting! Thanks for the investigation. I'll take that lead and look over it more on the weekend.

**Comment by zeeshanabid94** [comment]
I did some investigation and it is the ProxyActions that are broke the Mod. I found two issues:
- **Build Issue:** The public API of ProxyActions was changed. A method being used before is no longer part of the class's public API. Removing those fixed the build issue.
- **Proxy Actions not working:** This is a strange one. The ProxyActions are not working even if I used the same ProxyActions as the net tool. I am working on this issue.

Haven't been able to figure out why the actions don't work. But hopefully I get sometime over the week to look into the issue for longer and figure out what is happening.

**Comment by kendallroth** [comment]
No idea whether this code might help or not, but realized today that the ["Cim Route Highlighter"](https://github.com/Vexal/CitiesSkylines2/tree/master/EmploymentTracker) mod might also be performing a similar operation to select roads 🤷.

**Comment by zeeshanabid94** [comment]
Nah. It wasn't Cim Route Highlighter. I just had to enable the actions in the OnCreate method. 

Although, now that I think about it, it makes me wonder if the Cim Route Highlighter clashes with this tool.

**Comment by kendallroth** [comment]
> Nah. It wasn't Cim Route Highlighter. I just had to enable the actions in the OnCreate method. 
> 
> Although, now that I think about it, it makes me wonder if the Cim Route Highlighter clashes with this tool.

Yeah, my apologies, I was more meaning that maybe the code behind the mod might be useful for figuring out what had changed, but glad you were able to figure this out!

**Comment by zeeshanabid94** [comment]
New issue that is related: https://github.com/zeeshanabid94/ZoningToolkit/issues/6
