### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by kendallroth** [zeeshanabid94/ZoningToolkit#2]
> Let me prefix this by thanking you (effusively!) for this mod; it really is an absolute staple ❤️!

While using this mod (pre and post detailers patch), I have wondered about a couple potential UI tweaks/improvements. The panel currently takes a fair amount of space which often lead me to hide it; however, this then makes it harder to remember what the current setting was. If the panel could be condensed it may be easier to leave the panel open permanently 🤷.

A couple suggestions could be to condense the individual "zoning mode" and "update tool" buttons into icon form (similar to CS:1 upgrade tool), displaying the current setting icon _inside_ the panel toggle button (maybe as a configurable setting), and moving the button into the existing top-left toolbar (as a couple other mods do). I threw together a sample mockup of some of these options overlaid with on a screenshot. I have a fair amount of React experience (absolutely no CS:2 modding experience though...), but would be willing to experiment with a UI-related PR at some point if that would be of any interest 🤷.

Once again, a _huge_ thank-you for this mod, and looking forward to seeing what comes next!

![image](https://github.com/zeeshanabid94/ZoningToolkit/assets/12562420/8f78d6cc-6eea-489a-9a0b-dc688669c2d6)

![image](https://github.com/zeeshanabid94/ZoningToolkit/assets/12562420/8afdbd51-64d7-4782-b9ee-2a9db0af8b63)

**Comment by zeeshanabid94** [comment]
Wow! I am absolutely amazed and grateful for these UI screens! I am also getting more excited to see this sort of engagement!

I think your UI is far superior than what I have and I would be willing to work with you to get this done. I have had a really busy week but I'll get back into this over the weekend.

I'd be willing to take a look at the PR once you have made one. I am going to work on abstracting away the game and UI communication so that we can tie that in easily to your UI.

**Comment by kendallroth** [comment]
While looking over the current UI code, I noticed it focuses more on class-based React components, rather than hooks (modern approach). I was wondering whether this was intentional (ie. due to issues experienced with hook-based approach) or whether it was simply what you were more familiar with (ie. from past React experience)? I've noticed that the CS2 modding docs seem to be using the hook-based approach, and that they have a number of game-based hooks for functional components. Would you prefer that I stick to class-based approach for any experimentation I do, or would you be open to experimenting with functional components?

**Comment by zeeshanabid94** [comment]
Class based approach was intentional. I don't believe in the functional approach with react. Especially when things become bigger and complicated, functional approach becomes untenable. That's just my personal opinion. 

The game based hooks are probably important for us to use. I'm fine with functional components if it let's us use the game hooks. Though if we can use the game hooks with the class based approach, I'd like to stick to the class based approach.

These are just my thoughts though. What do you think about functional vs class based?

**Comment by zeeshanabid94** [comment]
Also, can functional components be written in typescript? I think I'd prefer functional components with type scripts because then at least we have static types to reason about.

**Comment by kendallroth** [comment]
> Class based approach was intentional. I don't believe in the functional approach with react. Especially when things become bigger and complicated, functional approach becomes untenable. That's just my personal opinion. [...] What do you think about functional vs class based?

I'm personally onboard the functional approach train, so I'll try not to let that influence my approach 😉! React has come a long, long way in the last few years _with the advent of hooks_, and functional approach is now far more reasonable than previously (when it lacked state, etc). In fact, functional components are now React's recommended approach 🤷. However, I do respect that everyone has their own opinions on that... Aside from lightly recommending taking another look at functional React, I will try to let it slide 😁.

> The game based hooks are probably important for us to use. I'm fine with functional components if it let's us use the game hooks. Though if we can use the game hooks with the class based approach, I'd like to stick to the class based approach.

I didn't look into whether or not the game-based hooks would provide any benefit (ie. shortening needed code) or not, so I'm not sure about them 🤷. They definitely might be able to make a few things easier (ie. binding to values, retrieving existing values exposed by CS2, etc), but that's a little deeper than I was looking into it at the moment (docs are rather sparse still). However, if the game-based hooks did prove valuable, I do not believe that hooks can be used with class-based components (although class based and functional components can be mixed in a code base).

> Also, can functional components be written in typescript? I think I'd prefer functional components with type scripts because then at least we have static types to reason about.

Yes, functional components can be written in TS (but so can classes, I think)?
